version: '3'
services:
  emdb:
    build:
      context: ./emdb
      dockerfile: Dockerfile.emdb
    ports:
      - "8081:8081"
  schedule:
    build:
      context: ./schedule
      dockerfile: Dockerfile.schedule
    ports:
      - "8082:8082"
  ticket:
    build:
      context: ./ticket
      dockerfile: Dockerfile.ticket
    ports:
      - "8083:8083"
  user:
    build:
      context: ./userManagement
      dockerfile: Dockerfile.user
    ports:
      - "8084:8084"
  venue:
    build:
      context: ./venueManagement
      dockerfile: Dockerfile.venue
    ports:
      - "8085:8085"